apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uoc-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false" 
spec:
  ingressClassName: nginx
  rules:
    - host: uoc.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-uoc
                port:
                  number: 3000