apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
     app: db-uoc
  name: db-uoc  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-uoc
  template:
    metadata:
      labels:
        app: db-uoc
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env-db
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env-db
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env-db
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env-db
          image: postgres:17.4
          name: dbhost
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: db-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: db-cm0
          name: db-cm0

