apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-uoc
  name: db-uoc
spec:
  type: ClusterIP
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: db-uoc
